pip install -q transformers==4.41.2
pip install -q bitsandbytes==0.43.1
pip install -q accelerate==0.31.0
pip install -q langchain==0.2.5
pip install -q langchainhub==0.1.20
pip install -q langchain-chroma==0.1.1
pip install -q langchain-community==0.2.5
pip install -q langchain-openai==0.1.9
pip install -q langchain_huggingface==0.0.3
pip install -q chainlit==1.1.304
pip install -q python-dotenv==1.0.1
pip install -q pypdf==4.2.0
npm install -g localtunnel
pip install -q numpy==1.24.4